[package]
name = "llms-from-scratch-rs"
version = "0.1.0"
edition = "2021"
author = "Val Andrei Fajardo <andrei@nerdai.io>"

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.7.2", features = ["cuda"] }
candle-nn = { git = "https://github.com/huggingface/candle.git", version = "0.7.2", features = ["cuda"] }
fancy-regex = "0.14.0"
rstest = "0.23.0"
tiktoken-rs = "0.6.0"
tokenizers = "0.20.1"
